name: Test on MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-bazel:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - run: sudo wget https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-darwin-amd64 -O /usr/local/bin/bazel
      - run: sudo chmod +x /usr/local/bin/bazel

      - run: bazel test -s rtorrent_test

      - run: bazel build -s rtorrent
      - run: cp bazel-bin/rtorrent rtorrent

      - uses: actions/upload-artifact@v2
        with:
          name: rtorrent-macos
          path: rtorrent

  end-to-end:
    needs: unit-bazel
    runs-on: macos-latest

    steps:
      - name: Copy rTorrent built in previous job
        uses: actions/download-artifact@v2
        with:
          name: rtorrent-macos

      - name: Install rTorrent to /usr/local/bin
        run: |
          sudo mv rtorrent /usr/local/bin/
          sudo chmod +x /usr/local/bin/rtorrent

      - name: Checkout Flood
        run: |
          git clone --depth 1 --branch master https://github.com/jesec/flood.git .

      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - run: npm ci --no-optional
      - run: npm run build

      - run: rtorrent || true

      - name: End-to-end test rTorrent with Flood's test suite
        uses: nick-invision/retry@v2
        with:
          max_attempts: 5
          timeout_minutes: 30
          command: npm t -- --selectProjects rtorrent --runTestsByPath server/routes/api/torrents.test.ts server/routes/api/client.test.ts || true
